name: 'Install and Cache Node Modules'
description: 'Some description'
inputs:
  caching:
    required: false
    description: "enable or disable"
    default: 'true'
outputs:
  status:
    value: 'Active'
    description: "Random status"
runs:
  using: 'composite'
  steps:
    - name: Cache node_modules
      if: inputs.caching == 'true'
      id: cashe-step
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-cache-file-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-cache-file-
          ${{ runner.os }}-
    - name: Display cashe
      run: echo '${{ toJSON(steps.cashe-step.outputs) }}'
      shell: bash
    - name: Install node_modules
      run: npm install
      shell: bash
